Generated from README.org, so if you have org-mode, go read that.
* Findings
* Daily Steps.
*** Day 2: Straight intp Prolog NOW!
*** Day 1ish
    - Read through [[https://pragprog.com/book/btlang/seven-languages-in-seven-weeks][Prag Prog]] Prolog chapter. Whet the apetitie.
    - Started this Prog Blog Log
    - Started _Learn Prolog NOW!_ below.
* _Learn Prolog NOW!_ [[http://www.learnprolognow.org/lpnpage.php?pagetype=html&pageid=lpn-htmlse1][Notes]]
*** Chapter 1
***** Section 1.1
      Only three basic constructs in Prolog:
      - facts
      - rules
      - queries
      A collection of facts and rules is called a *knowlage base* or *data base*
      Prolog is run by posing queries over the knowlage base.
******* Weirdness
        - The operator $:-$ is like a backwards if-then clause.  $A :-
          B$ means if $B$ obtains then $A$ must be true.
        - The comma is a logical ``and.'' Makes sense, but is very subtle.
        - Listing with multiple rules with the same head is expressing
          a logical disjuction.
          #+BEGIN_SRC prolog
            playsAirGuitar(butch):-
                happy(butch).
            playsAirGuitar(butch):-
                listens2Music(butch).
          #+END_SRC
          means Butch plays the air guitar when he's happy OR he's
          listening to music. Or a semicolon is a simpler way of
          saying the same thing:
          #+BEGIN_SRC prolog
            playsAirGuitar(butch):-
                happy(butch);
                listens2Music(butch).
          #+END_SRC
        - Any word beginning with a capital letter is a variable.
***** Section 1.2 Prolog Syntax
******* Atoms
        1. Charecter string beginning with a lower-case letter, can
           include underscore charecter, but must start with a
           lowercase letter.
        2. A sequence of charecters enclosed in quotes. This sequene
           is called the "atom name." Can have spaces, which, indeed
           is the point of the quotation marks.
        3. A string of special charecters. $\;$  $:-$ and $@=$ and $=====>$
           are all atoms, but some of these atoms have predefined meaning.
******* Numbers
        Prolog has both floating point numbers and Integers, but cares
        very little about them.  Integers will be talked about again
        in this book as they count things, floating points are already forgotten.
******* Variables
        - Start with an upper-case letter or an underscrore, followed
          by a string of alpha-numeric charecters and underscores.
        - $_$ --- the single underscore charecter --- is called ``the
          empty variable,'' and is special.
******* Complex Terms
        - Functor + sequence of arguments.
          - Arguments are in enclosed in parentheses, separated by commas.
          - Functor must be an atom, arguments can be any kind of term
          - Complex terms can have other complex terms nested (aka
            _recursivelly structured_ inside them:
            #+BEGIN_SRC prolog
              hide(X, father(father(father(father(butch)))))
            #+END_SRC
          - Number of arguments is called the _arity_
          - Predicates are refered to in documentation with
            name/arity:
            listens2Music/1
            love/2 and love/3 are distinct.
***** Section 1.3 Exercises
******* 1.1 Which are atoms, which are variables, which are niether?
        - vINCENT :: atom
        - Footmassage ::  variable
        - variable23 :: atom
        - Variable2000 :: variable
        - big_kahuna_burger :: atom
        - 'big kahuma burger' :: atom
        - 'Jules' :: atom
        - _Jules :: variable
        - '_Jules' :: atom
******* 1.2  Which are atoms, variables, complex terms, and which are not terms at all?
        - loves(Vincent, mia) :: loves/2
        - 'loves(Vincent, mia)' :: atom
        - Butch(boxer) :: --not a term.  Functor must be an atom.
        - boxer(Butch) :: boxer/1
        - and(big(burger),kahuna(burger)) :: and/2
        - _and(big(X), kahuna(X)) :: --not a term.  Functor must be an atom.
        - (Butch kills Vincent) :: ---not a term. Functor must be
             immedietly followed by parentheses enclosing arguments.
        - kills(Butch, Vincent) :: kills/2
        - kills(Butch, Vincent :: ---not a term. Missing closing parentesis.
******* 1.3 How many facts, rules, clauses, and predicates are there in this knowledge base?
        What are the heads of the rules, and what are the goals they
        contain?
        #+BEGIN_SRC prolog
          woman(vincent).
          woman(mia).
          man(jules).
          person(X):-  man(X);  woman(X).
          loves(X,Y):-  father(X,Y).
          father(Y,Z):-  man(Y),  son(Z,Y).
          father(Y,Z):-  man(Y),  daughter(Z,Y).
        #+END_SRC
        - Facts :: 3
        - Rules ::  4
          - heads :: 3 distinct with their goals:
            - person/1 :: 2 goals:
              - man/1
              - woman/1
            - loves/2 :: 1 goal
              - father/2
            - father/2 :: 2 goals
              - man/1
              - son/2
            - father/2 :: 2 goals
              - man/1
              - daughter/2
******* 1.4 Represent the following in Prolog
        - Butch is a killer. :: killer(butch).
        - Mia and Marsellus are married.  :: married(mia, marsellus).
        - Zed is dead. :: dead(zed).
        - Marsellus kills everyone who gives Mia a footmassage. ::
             gives_footmassage(X, mia) :- kills(marsellus, X).
        - Mia loves everyone who is a good dancer.  :: good_dancer(X)
             :- loves(mia, X).
        - Jules eats anything that is nutritious or tasty.  ::
             eats(jules) :- tasty(X) ; nutritious(X)
******* How does Prolog respond to the following queries, given the knowlage base:
        #+BEGIN_SRC prolog
          wizard(ron).
          hasWand(harry).
          quidditchPlayer(harry).
          wizard(X):-  hasBroom(X),  hasWand(X).
          hasBroom(X):-  quidditchPlayer(X).
        #+END_SRC
        - wizard(ron). :: true ; false.
        - witch(ron). :: ERROR: Undefined procedure: witch/1
        - quidditchPlayer(harry). :: true.
        - wizard(harry). :: true.
        - wizard(Y). ::  Y = ron ; Y = harry.
        - witch(Y). :: ERROR: Undefined procedure: witch/1
        
***** Section 1.4 Practical Session
      Practice with Prolog!
      $listing(something)$ gets you more info on that
      something. Just $?-listing$ gets you a whole bunch of stuff on
      swi-pl it seems.
                         
*** Chapter 2

***** Unification
      #+BEGIN_QUOTATION
      Two terms unify if they are the same term or if they contain
      variables that can be uniformly instantiated with terms in such
      a way that the resulting terms are equal.
      #+END_QUOTATION
      - atoms :: unify when they are the same: $a = a$ and $a = 'a'$
                 but $'b' = "b"$ returns false in  SWI-Prolog.
      - numbers ::  same as atoms: $42 = 42$ but not $'2' = 2$
      - complex terms :: $prop("subject") = prop("subject")$ is true,
                         but, $prop("subject") = prop("object")$
                         is not.
      - variables :: unify with anything that can be instantiated.
                     $X = a, X = b$ is false.
      - complex terms :: $k(s(g), Y) k(X,t(k))$
                         #+BEGIN_SRC prolog
                           ?- k(s(g),Y) = k(X,t(k)).
                           Y = t(k),
                           X = s(g).
                         #+END_SRC
******* Occurs check
        $father(X)  =  X$ works in Prolog. $X = father(X),  Y =
        father(Y),  X  =  Y$ can crash some systems, but not SWI!
        because Prolog doesn't check if the variable occurs in the
        term being unified, so a recursive unification is possible,
        though it seems to be discouraged. $unify_with_occurs_check/2$
        exists if there's a danger.
******* Programming with unification
        #+BEGIN_SRC prolog :tangle "./LearnNOW/Chapter_02/cart_points.pl"
          vertical(line(point(X, Y), point(X, Z))).
          horizontal(line(point(X,Y), point(Z,Y))).
        #+END_SRC
        horizontal(line(point(4,A), point(2,4))).
        A = 4.

        ?- horizontal(line(point(24,31),Q)).
        Q = point(_3876, 31).

***** Exercises
******* 2.2
        #+BEGIN_SRC prolog :tangle "./LearnNOW/Chapter_02/Ex2_2.pl"
          house_elf(dobby).
          witch(hermione).
          witch(rita_skeeter).
          witch('McGonagall').
          wizard(harry).
          magic(X):- house_elf(X).
          magic(Y):- wizard(Y).
          magic(X):- witch(X).
        #+END_SRC
        So, if you do this exercise, and omit the `wizard(harry).`
        line as in the book, swi-prolog will throw unpleasant errors,
        specifically ``Undefined procedure: wizard/1'' at you until
        you put it back.
        - ?- magic(house_elf). :: Generates an "Undefined procedure:
             wizard/1" error
        - ?- witch(hermione). :: true (from KB)
        - ?- wizard(harry) :: true
        - magic(wizard) :: ``Undefined procedure: wizard/1''
        - magic('McGonagall') :: true
*******  Ex. 2.3 Tiny lexicon, a mini grammar, with one syntactic rule:
        #+BEGIN_SRC prolog :tangle "./LearnNOW/Chapter_02/Ex2_3.pl"
          word(determiner, a).
          word(determiner, every).
          word(noun, criminal).
          word(noun, 'big kahuna burger').
          word(verb, eats).
          word(verb, likes).

          sentence(Word1, Word2, Word3, Word4, Word5):-
              word(determiner, Word1),
              word(noun, Word2),
              word(verb, Word3),
              word(determiner, Word4),
              word(noun, Word5).
        #+END_SRC
        Query: sentence(X1, X2, X3, X4, X5).
        First response: 
        #+BEGIN_SRC prolog :tangle no
          X1 = X4, X4 =a,
          X2 = X5 =, X5 = criminal,
          X3 = eats
        #+END_SRC
        Thus: ``A criminal eats a criminal.''
*******  Ex. 2.4
        Knowledge base represents a lexicon containing six Italian
        words:,
        #+BEGIN_SRC prolog :tangle "./LearnNOW/Chapter_02/Ex2_4.pl"
          word(astante,  a,s,t,a,n,t,e).
          word(astoria,  a,s,t,o,r,i,a).
          word(baratto,  b,a,r,a,t,t,o).
          word(cobalto,  c,o,b,a,l,t,o).
          word(pistola,  p,i,s,t,o,l,a).
          word(statale,  s,t,a,t,a,l,e). 
        #+END_SRC
        Write a predicate, crossword/6 telling how to fill in the
        grid.  First three arguments should be the vertical words,
        from left to right, the last three horizontal words from top
        to bottom.
        #+BEGIN_SRC prolog :tangle "./LearnNOW/Chapter_02/Ex2_4_answer.pl"
          crossword(V1, V2, V3, H1, H2, H3):-
              word(V1, V1C1, V1H1, V1C3, V1H2, V1C5, V1H3, V1C7),
              word(V2, V2C1, V2H1, V2C3, V2H2, V2C5, V2H3, V2C7),
              word(V3, V3C1, V3H1, V3C3, V3H2, V3C5, V3H3, V3C7),
              word(H1, H1C1, V1H1, H1C3, V2H1, H1C5, V3H1, H1C7),
              word(H2, H2C1, V1H2, H2C3, V2H2, H2C5, V3H2, H2C7),
              word(H3, H3C1, V1H3, H3C3, V2H3, H3C5, V3H3, H3C7).
         #+END_SRC
***** Practical Session
******* KB
        #+BEGIN_SRC prolog :tangle "./LearnNOW/Chapter_02/proof.pl"
          f(a).
          f(b).

          g(a).
          g(b).

          h(b).

          k(X):-
              f(X),
              g(X),
              h(X).
        #+END_SRC
        use trace/0 to run through the execution of the query
        $k(X)$. It's kinda cool. Add a term to the database using
        assert/1 and see the effect on execution.
        
